#!/bin/bash                                                                ain je
                                                                           ...3 m
## Author: Pierre
## Date: oct 2022

echo "starting Jenkins installation this will take a few min..."

systemctl enable firewalld
systemctl start firewalld
systemctl status firewalld


yum install java-11-openjdk-devel -y
curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | sudo tee /etc/yum.repos.d/jenkins.repo
sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
yum install jenkins -y
systemctl start jenkins
systemctl status jenkins                                                   5     
systemctl enable jenkins
sudo firewall-cmd --permanent --zone=public --add-port=8080/tcp
firewall-cmd --reload

echo "Jenkins is ready please get ip and type it on your browser"